/*
 * Razorpay APIs - OpenAPI 3.0
 *
 * Razorpay is an Indian payments solution provider that allows businesses to accept, process and disburse payments with its product suite. 
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetPaymentsResponse struct {
	Entity string `json:"entity,omitempty"`
	Count int32 `json:"count,omitempty"`
	Items []Payment `json:"items,omitempty"`
}
